version: '3'
services:
  web_tri3_csaq:
    image: java_springv1_tri3_csaq
    build: .
    ports:
      - "8555:8085"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/tri3_csaq_8555/volumes
